pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import *
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("reportada.urls", namespace="reportada_app")),
    path('login/', auth_views.LoginView.as_view(template_name='reportada/sesion.html')),
    #url(r'^api-auth/', include('rest_framework.urls')),
    #url(r'^accounts/', include('registration.urls')),
    #url(r'^accounts/', include('registration.backends.model_activation.urls')),
]

pizzeria/reportada/urls.py
from django.urls import path
from reportada import views
from django.contrib.auth.views import LogoutView
from django.conf.urls import url
from reportada.views import *

app_name = "reportada_app"

urlpatterns = [
	path('', views.index, name="index"),
	path('sesion/', views.sesion, name='sesion'),
    path('sucursales/', views.sucursales, name='sucursales'),
    path('paquetes/', views.paquetes, name='paquetes'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('armatupizza/', views.armatupizza, name='armatupizza'),
    path('googlemaps/', views.googlemaps, name='googlemaps'),
    path('googlemaps2/', views.googlemaps2, name='googlemaps2'),
    path('googlemaps3/', views.googlemaps2, name='googlemaps3'),
	path('registrar/', views.RegistroCliente.as_view(), name='registrar'),
	path('logout/', LogoutView.as_view(), {"next_page": settings.LOGOUT_REDIRECT_URL}, name="logout"),

]

pizzeria/accounts/models.py
from django.db import models

# Create your models here.

pizzeria/reportada/models.py
from django.db import models
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Create your models here.
class Registro(models.Model):
	first_name=models.CharField(settings.AUTH_USER_MODEL,max_length=150)
	last_name=models.CharField(max_length=150)
	email= models.EmailField(max_length=150, blank=True)
	username= models.CharField(max_length=150)
	password1=models.CharField(max_length=150)
	password2=models.CharField(max_length=150)

	

class Usuarios(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # username
    # first_name
    middle_name = models.CharField(max_length=150, blank=True)
    # last_name
    # email
    # password
    fecha_nacimiento = models.DateField(blank=True)
    # is_staff
    # is_active

class Direcciones(models.Model):
    usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    nombre_calle = models.CharField(max_length=40)
    tipo_calle = models.CharField(max_length=20)
    num_casa = models.CharField(max_length=6, blank=True)
    colonia = models.CharField(max_length=40)
    codigo_postal = models.CharField(max_length=6)
    ciudad = models.CharField(max_length=20)

class Empleados(models.Model):
    usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    curp = models.CharField(max_length=18)
    rfc = models.CharField(max_length=13)
    nss = models.CharField(max_length=11)
    sexo = models.CharField(max_length=1)

class Clientes(models.Model):
    METODOS_PAGO = [
        ('Efectivo', 'Efectivo'),
        ('Paypal', 'Paypal'),
        ('Tarjeta de Credito/Debito', 'Tarjeta de Credito/Debito'),
    ]
    usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    pago_por_defecto = models.CharField(max_length=25, choices=METODOS_PAGO)
    paypal = models.EmailField(max_length=64, blank=True)

class Cards(models.Model):
	cliente = models.ForeignKey(Clientes, on_delete=models.CASCADE)
	numero = models.CharField(max_length=16)
	ccv = models.CharField(max_length=4)

class Productos(models.Model):
    SIZE_PIZZA = [
        ('Individual', 'Individual'),
        ('Mediana', 'Mediana'),
        ('Grande', 'Grande'),
        ('Familiar', 'Familiar'),
    ]
    descripcion = models.CharField(max_length=128)
    precio = models.FloatField()
    size = models.CharField(max_length=10, choices=SIZE_PIZZA, blank=True)
    
class Ventas(models.Model):
    ESTATUS_VENTA = [
        ('Pendiente', 'Pendiente'),
        ('Cancelada', 'Cancelada'),
        ('Finalizada', 'Finalizada'),
    ]
    cliente = models.ForeignKey(Clientes, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Productos, through='VentasDetalle')
    estatus = models.CharField(max_length=10, choices=ESTATUS_VENTA)
    fecha = models.DateTimeField(auto_now_add=True)
    impuesto = models.FloatField()  # IVA en dinero    16%
    subtotal = models.FloatField()

class VentasDetalle(models.Model):
    venta = models.ForeignKey(Ventas, on_delete=models.CASCADE)
    producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

pizzeria/reportada/forms.py
from django import forms
from django.db import models
from .models import Registro
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class FormRegistro(UserCreationForm):
	first_name=forms.CharField(widget=forms.TextInput())
	last_name=forms.CharField(widget=forms.TextInput())
	email= forms.CharField(widget=forms.EmailInput())
	username= forms.CharField(widget=forms.TextInput())
	password1=forms.CharField(widget=forms.PasswordInput())
	password2=forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model=User
		fields=[
		"first_name",
		"last_name",
		"email",
		"username",
		"password1",
		"password2"
	]

class LoginForm(forms.Form):
	username=forms.CharField()
	password=forms.CharField(widget=forms.PasswordInput())

pizzeria/accounts/views.py
from django.shortcuts import render

# Create your views here.

pizzeria/reportada/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import *
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.views import generic
from django.http import HttpResponse
from django.template import RequestContext
# Create your views here.
def index(request):
    return render(request, 'reportada/index.html')

def sucursales(request):
    return render(request, 'reportada/sucursales.html')
def pizzas(request):
    return render(request, 'reportada/pizzas.html')
def paquetes(request):
    return render(request, 'reportada/paquetes.html')
def armatupizza(request):
    return render(request, 'reportada/armatupizza.html')
def googlemaps(request):
	return render(request, 'googlemaps/googlemaps.html')
def googlemaps2(request):
	return render(request, 'googlemaps/googlemaps2.html')
def googlemaps3(request):
	return render(request, 'googlemaps/googlemaps3.html')

class RegistroCliente(generic.CreateView):
	model=User
	template_name="accounts/registrar.html"
	form_class = FormRegistro
	success_url = reverse_lazy('reportada_app:sesion')

def sesion(request):
	message = None
	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			username = request.POST["username"]
			password = request.POST["password"]
			user=authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					message="Has iniciado sesión"
					return render(request, "reportada/index.html")
				else:
					message="Usuario incorrecto"
			else:
				message="Usuario o contraseña incorrecta"
	else:
		form=LoginForm()
	context={ 
		"form": form,
		"message": message,	
	}
	return render(request, "accounts/sesion.html", context)
# def login_view(request):
# 	if request.method=='POST':
# 		form=AuthenticationForm(data=request.POST)
# 		if form.is_valid():
# 			user=form.get_user()
# 			login(request, user)
# 			if 'next' in request.POST:
# 				return redirect(request.POST.get('next'))
# 			else:
# 				return redirect('reportada_app:index')
# 		else:
# 			form=AuthenticationForm()
# 		return render(request, 'reportada/index.html', {'form':form})

pizzeria/templates/accounts/sesion.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Inicia sesión{% endblock %}
<head>
	{% block head %}
		<link rel="stylesheet" href="{% static 'css/main.css' %}" >
		<link rel="stylesheet" href="{% static 'css/util.css' %}" >  
	{% endblock %}
</head>
{% block load %}
<div class="loader-page">
	<img src="{% static 'img/giphy3.gif' %}" >
</div>
{% endblock %}

{% block content %}
	
<div class="container-login100" style="background-image: url({% static 'img/6.jpg' %}); text-align: center;">
	<div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-20">
		<form method="POST" class="login100-form validate-form" action="{%url 'reportada_app:sesion' %}">
			{% csrf_token %}
			{% if request.GET.next %}
				<input type="hidden" name="next" value="{{request.GET.next}}">
			{% endif %}
			<span class="login100-form-title p-b-30 font-weight-bold">
				<i class="fas fa-user"></i> Inicia sesión
			</span>
			{% if message %}
				<b>{{message}}</b>
			{% endif %}
			<br>
			<br>

			<div class="form-group wrap-input100 validate-input  m-b-20" data-validate="Ingresa tu nombre de usuario" for="text">
				<input type="text" class="form-control input100" id="usuario1" aria-describedby="emailHelp" name="username" placeholder="Nombre de usuario">
				<span class="focus-input100"></span>
			</div>

			<div class="form-group wrap-input100 validate-input m-b-25" data-validate = "Ingresa tu contraseña" for="password">
				<input class="form-control input100" id="password1" type="password" aria-describedby="passwordHelp" name="password" placeholder="Contraseña">
				<span class="focus-input100"></span>
			</div>

			<div class="form-group form-check text-center p-t-8">
				<input type="checkbox" class="form-check-input" id="exampleCheck1">
				<label class="form-check-label text-muted" for="exampleCheck1">Recordarme</label>
			</div>

			<div class="text-center p-t-20 p-b-20">
				<div class="form-group">
					<input class="btn btn-primary" type="submit" value="Ingresar">
				</div>
			</div>

			<!-- <div class="dropdown-divider"></div>
			<div class="text-center p-t-20 p-b-20">
				<span class="txt1">
				O ingresa con:
				</span>
			</div>

			<div class="flex-c p-b-50">
				<a href="#" class="login100-social-item">
					<i class="fab fa-facebook-f"></i>
				</a>
				<a href="#" class="login100-social-item">
					<img src="{% static 'img/icon-google.png' %}" alt="GOOGLE">
				</a>
			</div> -->

			<div class="dropdown-divider"></div>	
		    <div class="text-center p-b-10">
		    	<a class="font-weight-bold">¿No tienes cuenta?</a>
		    </div>
            <div class="text-center">
            	<a href="{%url 'reportada_app:registrar' %}" class="btn btn-outline-secondary btn-lg btn-block">Registrate</a>
            </div>
            
			
		</form>
	</div>
</div>
{% endblock  %}

pizzeria/templates/footer.html
 {% load staticfiles %}
  <footer class="container-fluid bg-inverse unique-color-dark fondo">
    <div class="row text-white py-4 text-white">
      <div class="col-md-3">
        <img src="{% static 'img/Design1.svg' %}" alt="" width="70px" height="auto" class="float-left mr-3">
        <h4 class="lead">Pizzería "La Reportada"</h4>
        <footer class="blockquote-footer">Por <cite title="Source Title">team RED</cite></footer>
      </div>



      <div class="col-md-3">
        <h4 class="lead"></h4>
        <p></p>
      </div>
      <div class="col-md-3">
        <h4 class="lead"></h4>
        <p></p>
      </div>
      <div class="col-md-3">
        <h4 class="lead">Síguenos</h4>
        <a href="#"><span class="badge badge-primary">Facebook</span></a>
        <a href="#"><span class="badge badge-danger">Youtube</span></a>
      </div>
    </div>
  </footer>

pizzeria/templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-inverse bg-inverse navbar-toggleable-sm sticky-top menv">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{%url 'reportada_app:index' %}">
    <img src="{% static 'img/Design1.svg' %}" width="50" height="50"  class="d-inline-block align-top" alt="Logo Bootstrap">
    La Reportada
  </a>
  <div class="collapse navbar-collapse " id="navbarTogglerDemo01">
    <div class="navbar-nav mr-auto ml-auto text-center font-weight-bold"  style="font-size:17.5px; padding-top: 0.1px; padding-left: 30vw;">
      <a class="nav-item nav-link btn-outline-dark text-white" href="{%url 'reportada_app:index' %}" role="button">Inicio</a>
      <a class="nav-item nav-link btn-outline-dark text-white" href="{%url 'reportada_app:pizzas' %}" role="button">Pizzas</a>
      <a class="nav-item nav-link btn-outline-dark text-white" href="{%url 'reportada_app:paquetes' %}" role="button">Paquetes</a>
      <a class="nav-item nav-link btn-outline-dark text-white" href="{%url 'reportada_app:sucursales' %}" role="button">Sucursales</a>
      {% if request.user.is_authenticated %}
      
      <a class="nav-item nav-link btn-outline-dark text-white" href="{%url 'reportada_app:logout' %}" role="button" >Cerrar Sesión</a>
      <span style="padding-right: 15vw; "></span>
       <p class="nav-link btn-primary text-white" >Bienvenido {{ request.user.username }} </p> 
      {% else %}

        <a class="nav-item nav-link btn-outline-dark text-white" href="{%url 'reportada_app:sesion' %}" role="button" >Iniciar Sesión</a>
        <span style="padding-right: 30vw; "></span>
      {% endif %}
    </div>
  </div>
</nav>

pizzeria/templates/reportada/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Inicio{% endblock %}

{% block css %}
      .slider{
      background: url("{% static 'img/01.jpg' %}");
      height: 100vh;
      background-size: cover;
      background-position: center; 
      }
{% endblock %}
<!--Loader page -->
{% block load %}
<div class="loader-page">
  <img src="{% static 'img/giphy3.gif' %}" >
  </div>
{% endblock %}

{% block section %}

 <!-- <section class="container-fluid slider d-flex justify-content-center align-items-center">
    <h1 class="display-4" style="color: white" >Bienvenido</h1>
  </section> -->

  <div class="slider3d first">
  <div class="slider3d__wrapper">
    <div class="slider3d__inner">
      <div class="slider3d__rotater">
        <div class="slider3d__item">
      <!--icono llamar -->
      <div class="d-flex">
      <div class="ml-auto p-2">
      <a href="#">
      <button class="phone btn btn-warning"  type="button"  data-hover=" 6641234567 " data-active="I'M ACTIVE"><span> <i class='fas fa-phone-volume' style='font-size:20px'></i> LLAMAR </span></button>
      </a>
      </div>
      </div>
      <!--fin llamar-->
          <h2 class="slider3d__heading" data-text="SO HEADING">Bienvenido</h2>
        </div>
        <div class="slider3d__item">
      <!--icono llamar -->
      <div class="d-flex">
      <div class="ml-auto p-2">
      <a href="#">
      <button class="phone btn btn-warning"  type="button"  data-hover=" 6641234567 " data-active="I'M ACTIVE"><span> <i class='fas fa-phone-volume' style='font-size:20px'></i> LLAMAR </span></button>
      </a>
      </div>
      </div>
      <!--fin llamar-->
          <h2 class="slider3d__heading" data-text="MUCH ROTATION">Conoce nuestras promos</h2>
        </div>
        <div class="slider3d__item">
      <!--icono llamar -->
      <div class="d-flex">
      <div class="ml-auto p-2">
      <a href="#">
      <button class="phone btn btn-warning"  type="button"  data-hover=" 6641234567 " data-active="I'M ACTIVE"><span> <i class='fas fa-phone-volume' style='font-size:20px'></i> LLAMAR </span></button>
      </a>
      </div>
      </div>
      <!--fin llamar-->
          <h2 class="slider3d__heading" data-text="VERY 3D">A tu gusto</h2>
        </div>
        <div class="slider3d__item">
      <!--icono llamar -->
      <div class="d-flex">
      <div class="ml-auto p-2">
      <a href="#">
      <button class="phone btn btn-warning"  type="button"  data-hover=" 6641234567 " data-active="I'M ACTIVE"><span> <i class='fas fa-phone-volume' style='font-size:20px'></i> LLAMAR </span></button>
      </a>
      </div>
      </div>
      <!--fin llamar-->
          <h2 class="slider3d__heading" data-text="WOW WOW!">WOW WOW!</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="slider3d__controls">
    <div class="slider3d__handle">
      <div class="slider3d__handle__inner">
        <div class="slider3d__handle__rotater">
          <div class="slider3d__handle__item active">Bienvenidos</div>
          <div class="slider3d__handle__item">Promos</div>
          <div class="slider3d__handle__item">Al gusto</div>
          <div class="slider3d__handle__item">wow!</div>
          <div class="slider3d__handle__item">Bienvenidos</div>
        </div>
      </div>
    </div>
    <div class="slider3d__control m--up"></div>
    <div class="slider3d__control m--down"></div>
  </div>


</div>

{% endblock %}

{% block content %}
  
<!--entregar y recoger -->
<section class="container my-5 py-0">
<div class="card text-white  mb-3 cont-gen ">
  <div class="card-header cont-gene">
    <ul class="nav nav-tabs card-header-tabs justify-content-center opcion" id="myTab" role="tablist">
      <li class="nav-item opcione">
        <a class="nav-link active  opciones" id="entrega-tab" data-toggle="tab" href="#entrega"role="tab" aria-controls="entrega"aria-selected="true"><img src="{% static 'img/entrega.gif' %}" width=30 heigth=auto class="icon-entrega" > Entrega a Domicilio</a>
      </li>
      <li class="nav-item opcione" >
        <a class="nav-link opciones" id="recoger-tab" data-toggle="tab" href="#recoge" role="tab" aria-controls="recoger" aria-selected="false"><img src="{% static 'img/recoger.gif' %}" width=30 heigth=auto class="icon-recoge">  Recoger en  Tienda </a>
      </li>
    </ul>
   </div>

  <div class="card-body tab-content text-opcion" id="myTabContent">
<div class=" tab-pane fade show active" id="entrega" role="tabpanel" aria-labelledby="entrega-tab">
    <h5 class="card-title tit-le">¿Dónde entregamos tu pedido?</h5>
    <p class="card-text">
    <div class="input-group mb-3 ">
  <input type="text" class="form-control" placeholder="Ingresa tu dirección" aria-label="Recipient's username" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <button class="btn btn-success btn-block" type="button">Ordenar ahora</button>
  </div>
</div>    
    <p class="text-primary text-left"><a href="" class="card-link"><i class="fas fa-map-marker-alt"></i></i> Utiliza mi ubicación</a></p>
    </p>
</div>
<div class="tab-pane fade" id="recoge" role="tabpanel" aria-labelledby="recoge-tab">
    <h5 class="card-title tit-le">Encuentra tu tienda mas cercana:</h5>
    <p class="card-text">
    <div class="input-group mb-3 ">
  <input type="text" class="form-control" placeholder="Ingresa tu CP o colonia" aria-label="Recipient's username" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <button class="btn btn-success btn-block" type="button">Ordenar ahora</button>
  </div>
</div>    
    <p class="text-primary text-left"><a href="" class="card-link"><i class="fas fa-map-marker-alt"></i></i> Utiliza mi ubicación</a></p>
    </p>
</div>
  </div>
</div>
</section>
<!--fin card-->
<div class="dropdown-divider"></div>
<!-- PROMOs-->
<section class="container my-5 py-2">
  <h3 class="text-uppercase text-center mb-4">  </h3>

  <p class="lead text-center mb-5" style="font-size: 1.5rem;"> NUESTRO MENÚ </p>
  <div class="card-deck text-white" >
    <div class="card">

      <img class="card-img-top img-fluid" src="{% static 'img/1.jpg' %}" alt="Card image cap">

      <div class="card-block" style="background-color:#58b369; text-align: center;">
        <h4 class="card-title">Pizzas</h4>
        <br>
        <a class="btn btn-outline-light" href="{%url 'reportada_app:pizzas' %}" role="button">Conocelas!</a>
      </div>
    </div>
    <div class="card">
      <img class="card-img-top img-fluid" src="{% static 'img/5.jpg' %}" alt="Card image cap">
      <div class="card-block" style="background-color:#d45456; text-align: center;">
        <h4 class="card-title">Pastas</h4>
        <br>
        <a class="btn btn-outline-light" href="#" role="button">Conocelas!</a>
      </div>
    </div>
    <div class="card">
      <img class="card-img-top img-fluid" src="{% static 'img/6.jpg' %}"alt="Card image cap">
      <div class="card-block" style="background-color:#41a8bc; text-align: center;">
        <h4 class="card-title">Antojos</h4>
        <br>
        <a class="btn btn-outline-light" href="#" role="button">Conocelos!</a>
      </div>
    </div>
  </div>
  </section>
  <!-- fin Cards -->
  <!-- START THE FEATURETTES -->

      <div class="container my-5">
        <hr class="">
        <br><br><br>
                  <h2 class="lead text-center mb-5" style="font-size: 1.5rem;"> NUESTRAS PROMOCIONES MÁS POPULARES </h2>
        <div class="row d-flex align-items-center my-5 py-5">
          <div class="col-md-7">
            <h2 class="display-4">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
            <p class="lead">Donec ullamcorper .......</p>
          </div>
          <div class="col-md-5">
            <img class=" img-fluid mx-auto" src="{% static 'img/12.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>
        
        <hr class="">
        
        <div class="row d-flex align-items-center my-5 py-5">
          <div class="col-md-7 push-md-5">
            <h2 class="display-4">Oh yeah, it's that good.<span class="text-muted">See for yourself.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum ......</p>
          </div>
          <div class="col-md-5 pull-md-7">
            <img class=" img-fluid mx-auto" src="{% static 'img/9.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>
        
        <hr class="">
        
        <div class="row d-flex align-items-center my-5 py-5">
          <div class="col-md-7">
            <h2 class="display-4">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis .....</p>
          </div>
          <div class="col-md-5">
            <img class=" img-fluid mx-auto" src="{% static 'img/2.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>
        
        
      </div>

      <!-- /END THE FEATURETTES -->

  
{% endblock  %}

pizzeria/templates/reportada/sucursales.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Sucursales{% endblock %}
<!--Loader page -->
{% block load %}
<div class="loader-page">
  <img src="{% static 'img/giphy3.gif' %}" >
  </div>
{% endblock %}

{% block content %}
<!-- sucursales-->
<section class="container my-5 py-2">

  <p class="lead text-center font-weight-bold mb-5" style="font-size: 1.5rem;"><i class="fas fa-store-alt" style=" color:#0b0101b3;" ></i> NUESTRAS SUCURSALES </p>
  <div class="dropdown-divider"></div>

  <div class="card-deck text-dark" > 
<div class="card mb-3 bg-ligth" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{% static 'img/13.jpg' %}" class="card-img">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title font-weight-bold">PLAYAS DE TIJUANA</h5>
        <p class="card-text"> Tel. (664) 630 9099</p>
        <p class="card-text">PASEO PEDREGAL NO. 1302, LOCAL 13-A, Col. COL. PLAYAS DE TIJUANA, 22200, BAJA CALIFORNIA, Tijuana</p>
        
      </div>
    </div>
    <a class="btn btn-outline-primary btn-lg btn-block" href="{%url 'reportada_app:googlemaps' %}" >Ver en mapa</a>
        
    
  </div>
</div>

<div class="card mb-3 bg-ligth" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{% static 'img/7.jpg' %}" class="card-img ">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title font-weight-bold">ZONA RÍO</h5>
        <p class="card-text"> Tel. (664) 634 2200</p>
        <p class="card-text">PASEO DE LOS HEROES NO. 10493, Col. ZONA RIO, 22320, BAJA CALIFORNIA, Tijuana</p>
        
      </div>
    </div>
    <a class="btn btn-outline-primary btn-lg btn-block" href="{%url 'reportada_app:googlemaps2' %}" >Ver en mapa</a>
  </div>
</div>

  </div>

<!-- -->
 <div class="card-deck text-dark" > 
<div class="card mb-3 bg-ligth" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{% static 'img/14.png' %}" class="card-img">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title font-weight-bold">REVOLUCIÓN</h5>
        <p class="card-text"> Tel. (664) 685 9000</p>
        <p class="card-text">AV. REVOLUCION NO. 885, Col. ZONA CENTRO, 22000, BAJA CALIFORNIA, Tijuana</p>
        
      </div>
    </div>
    <a class="btn btn-outline-primary btn-lg btn-block" href="{%url 'reportada_app:googlemaps3' %}" >Ver en mapa</a>
  </div>
</div>



  </div>
<!---->


  </section>
  <!-- fin Cards -->

{% endblock  %}